Revert "Merge branch 'bookworm' into master"
This reverts commit c82ec6e83067fbb7e36677f8b86a362b9c79792c, reversing
changes made to 8dd585ad947d6f034bb9499b94b14bc7cf8c7930.

diff --git a/image/overlayctl b/image/overlayctl
--- a/image/overlayctl
+++ b/image/overlayctl
@@ -19,32 +19,32 @@
 
 modify_boot_cmdline()
 {
-    if [ ! -e /boot/firmware/cmdline.txt ] ; then
+    if [ ! -e /boot/cmdline.txt ] ; then
         umount_boot=yes
-        mount /boot/firmware || exit 1
+        mount /boot || exit 1
     fi
-    if [ ! -e /boot/firmware/cmdline.txt ] ; then
-        echo "/boot/firmware/cmdline.txt missing"
+    if [ ! -e /boot/cmdline.txt ] ; then
+        echo "/boot/cmdline.txt missing"
         exit 1
     fi
-    if [ ! -w /boot/firmware ] ; then
+    if [ ! -w /boot ] ; then
         remount_boot_ro=yes
-        mount -o remount,rw /boot/firmware || exit 1
+        mount -o remount,rw /boot || exit 1
     fi
-    if ! grep -q '/sbin/init-overlay' /boot/firmware/cmdline.txt ; then
-        cp /boot/firmware/cmdline.txt /boot/firmware/cmdline.bak
+    if ! grep -q '/sbin/init-overlay' /boot/cmdline.txt ; then
+        cp /boot/cmdline.txt /boot/cmdline.bak
     fi
-    rm -f /boot/firmware/cmdline.new
+    rm -f /boot/cmdline.new
     sed -e 's/\( \|^\)\(ro\|rw\)\( \|$\)/ /g' \
         -e 's/\( \|^\)\(init=[^ ]*\)\( \|$\)/ /g' \
-        -e 's/^ //' -e 's/ $//' /boot/firmware/cmdline.txt \
+        -e 's/^ //' -e 's/ $//' /boot/cmdline.txt \
         -e 's#^\(.*root=.*\)$#\1'"$1"'#'\
-        >/boot/firmware/cmdline.new
-    mv /boot/firmware/cmdline.new /boot/firmware/cmdline.txt
+        >/boot/cmdline.new
+    mv /boot/cmdline.new /boot/cmdline.txt
     if [ -n "$umount_boot" ] ; then
-        umount /boot/firmware
+        umount /boot
     elif [ -n "$remount_boot_ro" ] ; then
-        mount -o remount,ro /boot/firmware
+        mount -o remount,ro /boot
     fi
 }
 
